server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/data
    username: sa
    password: password
#    schema: classpath:schema.sql
#    data: classpath:import.sql
    initialization-mode: always